// flow-typed signature: 0edca8586726d8a16ff0c3cf71470caf
// flow-typed version: <<STUB>>/babel-plugin-transform-es2015-typeof-symbol_v^6.8.0/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-es2015-typeof-symbol'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-es2015-typeof-symbol' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-es2015-typeof-symbol/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-es2015-typeof-symbol/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-es2015-typeof-symbol/lib/index'>;
}
