// flow-typed signature: e6ee46b35ae800f68bd844eeb1038c25
// flow-typed version: <<STUB>>/babel-preset-node5_v^10.2.0/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-node5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-node5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-node5/index' {
  declare module.exports: $Exports<'babel-preset-node5'>;
}
declare module 'babel-preset-node5/index.js' {
  declare module.exports: $Exports<'babel-preset-node5'>;
}
