// flow-typed signature: 3f9b4a4f04d5c9eaa5cb48298ff27be4
// flow-typed version: <<STUB>>/death_v^1.0.0/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'death'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'death' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'death/app' {
  declare module.exports: any;
}

declare module 'death/lib/death' {
  declare module.exports: any;
}

declare module 'death/test/death.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'death/app.js' {
  declare module.exports: $Exports<'death/app'>;
}
declare module 'death/lib/death.js' {
  declare module.exports: $Exports<'death/lib/death'>;
}
declare module 'death/test/death.test.js' {
  declare module.exports: $Exports<'death/test/death.test'>;
}
