// flow-typed signature: 8e65a477b5dcb7d4dfd3393ea2849b13
// flow-typed version: <<STUB>>/detect-indent_v^5.0.0/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'detect-indent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'detect-indent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'detect-indent/index' {
  declare module.exports: $Exports<'detect-indent'>;
}
declare module 'detect-indent/index.js' {
  declare module.exports: $Exports<'detect-indent'>;
}
