// flow-typed signature: df8a7db4f93155cd57c2a1c498aa13b5
// flow-typed version: <<STUB>>/eslint-config-fbjs_v^1.0.0/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-fbjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-fbjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-fbjs/strict' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-fbjs/index' {
  declare module.exports: $Exports<'eslint-config-fbjs'>;
}
declare module 'eslint-config-fbjs/index.js' {
  declare module.exports: $Exports<'eslint-config-fbjs'>;
}
declare module 'eslint-config-fbjs/strict.js' {
  declare module.exports: $Exports<'eslint-config-fbjs/strict'>;
}
