// flow-typed signature: b1e687f120eb4e02dbf98a6c195b5b53
// flow-typed version: <<STUB>>/is-builtin-module_v^1.0.0/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-builtin-module'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-builtin-module' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'is-builtin-module/index' {
  declare module.exports: $Exports<'is-builtin-module'>;
}
declare module 'is-builtin-module/index.js' {
  declare module.exports: $Exports<'is-builtin-module'>;
}
