// flow-typed signature: 847d27051cfd31522995bee52b9a21c7
// flow-typed version: <<STUB>>/loud-rejection_v^1.2.0/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loud-rejection'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'loud-rejection' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loud-rejection/api' {
  declare module.exports: any;
}

declare module 'loud-rejection/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loud-rejection/api.js' {
  declare module.exports: $Exports<'loud-rejection/api'>;
}
declare module 'loud-rejection/index' {
  declare module.exports: $Exports<'loud-rejection'>;
}
declare module 'loud-rejection/index.js' {
  declare module.exports: $Exports<'loud-rejection'>;
}
declare module 'loud-rejection/register.js' {
  declare module.exports: $Exports<'loud-rejection/register'>;
}
