// flow-typed signature: c68d871c4d9f042e55595dcec610ca43
// flow-typed version: <<STUB>>/mock-stdin_v^0.3.0/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mock-stdin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mock-stdin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mock-stdin/lib/index' {
  declare module.exports: any;
}

declare module 'mock-stdin/lib/mock/stdin' {
  declare module.exports: any;
}

declare module 'mock-stdin/test/stdin.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mock-stdin/lib/index.js' {
  declare module.exports: $Exports<'mock-stdin/lib/index'>;
}
declare module 'mock-stdin/lib/mock/stdin.js' {
  declare module.exports: $Exports<'mock-stdin/lib/mock/stdin'>;
}
declare module 'mock-stdin/test/stdin.spec.js' {
  declare module.exports: $Exports<'mock-stdin/test/stdin.spec'>;
}
