// flow-typed signature: 697865dca521f175dd351e50e16bd7dd
// flow-typed version: <<STUB>>/read_v^1.0.7/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'read'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'read' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'read/lib/read' {
  declare module.exports: any;
}

// Filename aliases
declare module 'read/lib/read.js' {
  declare module.exports: $Exports<'read/lib/read'>;
}
