// flow-typed signature: fda0798d7a6ab01623dbc8fde982e3d4
// flow-typed version: <<STUB>>/rimraf_v^2.5.0/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rimraf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rimraf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rimraf/bin' {
  declare module.exports: any;
}

declare module 'rimraf/rimraf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rimraf/bin.js' {
  declare module.exports: $Exports<'rimraf/bin'>;
}
declare module 'rimraf/rimraf.js' {
  declare module.exports: $Exports<'rimraf/rimraf'>;
}
